Pin go-plugin version A change was introduced to go-plugin which causes our plugin initialization to bail out, claiming that the plugin is not gRPC compat. See https://github.com/hashicorp/go-plugin/issues/57
Of note, the go-plugin tests are also failing on master when using either go 1.8 or 1.9.

```
--- FAIL: TestClient_logger (0.25s)
    --- FAIL: TestClient_logger/grpc (0.02s)
    	client_test.go:882: err should be nil, got plugin exited before we could connect
--- FAIL: TestGRPCClient_App (0.00s)
	testing.go:127: err: "test" is not a GRPC-compatible plugin
--- FAIL: TestGRPCClient_Ping (0.00s)
	testing.go:127: err: "test" is not a GRPC-compatible plugin
FAIL
exit status 1
FAIL	github.com/hashicorp/go-plugin	5.002s
```

/cc @mitchellh