Fix timezone mismatch in test
For me the test currently fails with:
--- FAIL: TestGooglePublicKeyRetriever (0.00s)
    --- FAIL: TestGooglePublicKeyRetriever/TestSuccess (0.00s)
        google_public_key_retriever_test.go:115:
                Error Trace:    google_public_key_retriever_test.go:115
                Error:          Not equal:
                                expected: "2018-06-21T01:53:33Z"
                                actual  : "2018-06-21T02:53:33+01:00"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -2018-06-21T01:53:33Z
                                +2018-06-21T02:53:33+01:00
                Test:           TestGooglePublicKeyRetriever/TestSuccess
FAIL

Since we end up comparing this with a timestamp in UTC it's probably
better to just create it in UTC to begin with.

Signed-off-by: Sorin Dumitru <sdumitru@bloomberg.net>