integration: wait for both TCP and UDS server endpoints
Noticed in the envoy suite that even though the server was ready we
still failed to fetch bundle for bootstrapping the agent:

```
downstream-federated-spire-server-1  | time="2026-05-24T06:43:57Z" level=info msg="Starting Server APIs" address="[::]:8081" network=tcp subsystem_name=endpoints
[2026-05-24T06:43:57Z] bootstrapping downstream federated agent...
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix ///tmp/spire-server/private/api.sock: connect: no such file or directory"
[2026-05-24T06:43:57Z] step 00-test-envoy-releases.sh failed
```

Since the CLI uses the UDS socket, it still failed even if the TCP
endpoint was available. Wait for both TCP and UDS before continuing.

Signed-off-by: Sorin Dumitru <sorin@returnze.ro>